language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g npm
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
script:
  - npm test
after_script:
  - npm run coveralls
notifications:
  email: false
sudo: false
