language: node_js
node_js:
  - "0.10"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm
  - npm install -g karma
  - npm install -g karma-chrome-launcher
  - npm install -g karma-jasmine
script:
  - npm test
notifications:
  email: false
sudo: false
